In [2]:
# Import necessary python libraries
import pandas as pd
import re

In [2]:
# Read raw data file
sgx = pd.read_excel("data/raw_sgx_data.xlsx")
sgx

,Company name Latin alphabet,"NACE Rev. 2, core code (4 digits)",Consolidation code,Total current assets\nUSD 2023,Total current assets\nUSD 2022,Total current assets\nUSD 2021,Total current assets\nUSD 2020,Total current assets\nUSD 2019,Total current assets\nUSD 2018,Total current assets\nUSD 2017,...,Cash & Cash Equivalents at the End of Period\nUSD 2013,Cash & Cash Equivalents at the End of Period\nUSD 2012,Cash & Cash Equivalents at the End of Period\nUSD 2011,Cash & Cash Equivalents at the End of Period\nUSD 2010,Cash & Cash Equivalents at the End of Period\nUSD 2009,Cash & Cash Equivalents at the End of Period\nUSD 2008,Cash & Cash Equivalents at the End of Period\nUSD 2007,Cash & Cash Equivalents at the End of Period\nUSD 2006,Cash & Cash Equivalents at the End of Period\nUSD 2005,Cash & Cash Equivalents at the End of Period\nUSD 2004
0,WILMAR INTERNATIONAL LIMITED,1041.0,C1,34373692000,32632410000,31814998000,27923570000,25583701000,26290404000,22579397000,...,2237232000,1528453000,1279658000,400475000,392263000,1103696000,444886000,-94081000,-101230000,3603868.301392
1,OLAM GROUP LIMITED,NaN,C1,17225670747.034698,15858883280.3866,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
2,FLEX LIMITED,2612.0,C1,n.a.,16021000000,14337000000,11363000000,9086270000,9103432000,9170414000,...,1593728000,1587087000,1518329000,1748471000,1927556000,1821886000,1719948000,714525000,942859000,869258000
3,JARDINE CYCLE & CARRIAGE LTD,4519.0,C1,11564100000,12131100000,11813500000,10056700000,10274500000,10107700000,9833700000,...,1601000000,1201000000,1510200000,847800000,962100000,839100000,672100000,551900000,491000000,177000000
4,CHINA AVIATION OIL (SINGAPORE) CORP LTD,4671.0,C1,n.a.,1205905000,1227737000,1567111000,1480610000,1330707000,1575915000,...,56299000,81144000,88065000,57988000,182192000,153102000,300472000,85376000,28657613.694668,2484392.227471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,PRINCIPAL S&P ETHICAL ASIA PACIFIC DIVIDEND ETF,6430.0,NF,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
601,GLOBAL INVESTMENTS LIMITED,6619.0,C1,76748826.021373,74323216.914833,73032480.209112,74967855.558395,92773161.569118,75400059.378862,99939396.802247,...,16079981.269956,20031057.97267,32417927.886844,15643633.756697,19594556.260526,55742080.205917,87753951.332152,42342240.832508,n.a.,n.a.
602,I M QUARRIES LIMITED,8552.0,C1,n.a.,0,480271.908641,482482.197881,466764.930487,553875.669301,791339.493155,...,0,0,407773.454666,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
603,ABF PAN ASIA BOND INDEX FUND,NaN,NF,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
604,YANGI FUND,6420.0,NF,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.

In [3]:
# Removing "\nth" pattern and ".1" pattern (for duplicated column names) from the column names
sgx.columns = pd.Index([re.sub(pattern= "\.\d?$", repl= "", string= 
                               re.sub(pattern= " ?\n(th)? ?", repl= " ", string= col)) for col in sgx.columns])

sgx = sgx.loc[:, ~sgx.columns.duplicated()]

In [4]:
# Lengthening dataframe using columns with time periods

id_vars = ['Company name Latin alphabet', 'NACE Rev. 2, core code (4 digits)', 'Consolidation code']

melted_sgx = pd.melt(sgx, id_vars= id_vars)

melted_sgx["year"] = melted_sgx["variable"].str.extract(r"(\d{4})$")[0]
melted_sgx["variable"] = melted_sgx["variable"].str.replace("\s+\d{4}$|USD", "", regex= True)

melted_sgx

,Company name Latin alphabet,"NACE Rev. 2, core code (4 digits)",Consolidation code,variable,value,year
0,WILMAR INTERNATIONAL LIMITED,1041.0,C1,Total current assets,34373692000,2023
1,OLAM GROUP LIMITED,NaN,C1,Total current assets,17225670747.034698,2023
2,FLEX LIMITED,2612.0,C1,Total current assets,n.a.,2023
3,JARDINE CYCLE & CARRIAGE LTD,4519.0,C1,Total current assets,11564100000,2023
4,CHINA AVIATION OIL (SINGAPORE) CORP LTD,4671.0,C1,Total current assets,n.a.,2023
...,...,...,...,...,...,...
1827095,PRINCIPAL S&P ETHICAL ASIA PACIFIC DIVIDEND ETF,6430.0,NF,Cash & Cash Equivalents at the End of Period,n.a.,2004
1827096,GLOBAL INVESTMENTS LIMITED,6619.0,C1,Cash & Cash Equivalents at the End of Period,n.a.,2004
1827097,I M QUARRIES LIMITED,8552.0,C1,Cash & Cash Equivalents at the End of Period,n.a.,2004
1827098,ABF PAN ASIA BOND INDEX FUND,NaN,NF,Cash & Cash Equivalents at the End of Period,n.a.,2004
1827099,YANGI FUND,6420.0,NF,Cash & Cash Equivalents at the End of Period,n.a.,2004

In [5]:
pivoted_sgx = melted_sgx.pivot(index= id_vars + ["year"], columns= "variable",values= "value").reset_index().rename_axis(None, axis=1)
pivoted_sgx

,Company name Latin alphabet,"NACE Rev. 2, core code (4 digits)",Consolidation code,year,Accounts receivable,Accumulated depreciation - No breakdown,Accumulated depreciation on buildings,Accumulated depreciation on land,Accumulated depreciation on leased assets,"Accumulated depreciation on other property, plant & equipment",...,Total other current liabilities,Total other non-current assets,Total other non-current liabilities,Total others current assets,Total shareholders' equity,Trade creditors,Transportation equipment,Treasury shares,Unusual & exceptional income (expenses),Work in progress
0,5E RESOURCES LTD,3900.0,C1,2004,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
1,5E RESOURCES LTD,3900.0,C1,2005,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
2,5E RESOURCES LTD,3900.0,C1,2006,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
3,5E RESOURCES LTD,3900.0,C1,2007,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
4,5E RESOURCES LTD,3900.0,C1,2008,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12095,ZHONGXIN FRUIT AND JUICE LIMITED,1039.0,C1,2019,n.a.,n.a.,-3855653.379798,n.a.,n.a.,-432224.627256,...,9330692.829371,924302.462667,32620.726585,9413118.415296,11931322.005093,192229.281664,317178.314745,n.a.,2475.680143,466301.636279
12096,ZHONGXIN FRUIT AND JUICE LIMITED,1039.0,C1,2020,n.a.,n.a.,-4074503.943145,n.a.,-335875.285983,-356107.032359,...,10067203.811884,1455978.335321,30842.802167,16384177.545607,12065053.396285,329933.09474,345071.534336,n.a.,n.a.,472404.203832
12097,ZHONGXIN FRUIT AND JUICE LIMITED,1039.0,C1,2021,1857.901454,n.a.,-4785334.844947,n.a.,-396507.135302,-451624.878436,...,15766771.03889,1627986.149043,32822.925687,12392047.872871,12603693.813503,230534.605414,395887.834817,n.a.,n.a.,409976.920843
12098,ZHONGXIN FRUIT AND JUICE LIMITED,1039.0,C1,2022,14098553.819001,n.a.,-4931439.227164,n.a.,-410318.447888,-498297.175884,...,7944075.839996,2081466.170847,31666.367292,796439.011335,19238662.457049,252135.981083,381938.21305,n.a.,n.a.,432574.526787
12099,ZHONGXIN FRUIT AND JUICE LIMITED,1039.0,C1,2023,12662561.843425,n.a.,-4837678.765491,n.a.,-404115.522534,-515543.422237,...,8433673.333421,1698827.830583,28373.482496,5692602.094859,18562042.436868,316102.632657,352189.29486,n.a.,4407.531261,370094.890609

In [6]:
pivoted_sgx = pivoted_sgx.drop(columns= [col for col in pivoted_sgx.columns if pivoted_sgx[col].eq("n.a.").all()])

In [17]:
pivoted_sgx.to_csv("Data/sgx_data.csv")

NameError: name 'pivoted_sgx' is not defined

## Filter out usable fields

In [3]:
sgx = pd.read_csv("Data/sgx_data.csv")
sgx

,Unnamed: 0,Company name Latin alphabet,"NACE Rev. 2, core code (4 digits)",Consolidation code,year,Accounts receivable,Accumulated depreciation - No breakdown,Accumulated depreciation on buildings,Accumulated depreciation on land,Accumulated depreciation on leased assets,...,Total other current liabilities,Total other non-current assets,Total other non-current liabilities,Total others current assets,Total shareholders' equity,Trade creditors,Transportation equipment,Treasury shares,Unusual & exceptional income (expenses),Work in progress
0,0,5E RESOURCES LTD,3900.0,C1,2004,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
1,1,5E RESOURCES LTD,3900.0,C1,2005,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
2,2,5E RESOURCES LTD,3900.0,C1,2006,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
3,3,5E RESOURCES LTD,3900.0,C1,2007,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
4,4,5E RESOURCES LTD,3900.0,C1,2008,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12095,12095,ZHONGXIN FRUIT AND JUICE LIMITED,1039.0,C1,2019,n.a.,n.a.,-3855653.37979794,n.a.,n.a.,...,9330692.8293705,924302.462667227,32620.7265853882,9413118.41529608,11931322.0050931,192229.281663895,317178.314745426,n.a.,2475.68014264107,466301.636278629
12096,12096,ZHONGXIN FRUIT AND JUICE LIMITED,1039.0,C1,2020,n.a.,n.a.,-4074503.94314528,n.a.,-335875.285983086,...,10067203.8118839,1455978.33532095,30842.8021669388,16384177.5456071,12065053.3962846,329933.094739914,345071.534335613,n.a.,n.a.,472404.20383215
12097,12097,ZHONGXIN FRUIT AND JUICE LIMITED,1039.0,C1,2021,1857.90145397186,n.a.,-4785334.84494686,n.a.,-396507.135301828,...,15766771.0388899,1627986.14904284,32822.9256868362,12392047.8728712,12603693.8135028,230534.605413675,395887.834817171,n.a.,n.a.,409976.920843124
12098,12098,ZHONGXIN FRUIT AND JUICE LIMITED,1039.0,C1,2022,14098553.8190007,n.a.,-4931439.22716379,n.a.,-410318.447887897,...,7944075.83999634,2081466.17084742,31666.3672924042,796439.011335373,19238662.4570489,252135.981082916,381938.213050365,n.a.,n.a.,432574.526786804
12099,12099,ZHONGXIN FRUIT AND JUICE LIMITED,1039.0,C1,2023,12662561.843425,n.a.,-4837678.76549065,n.a.,-404115.522533655,...,8433673.33342135,1698827.83058286,28373.4824955463,5692602.09485888,18562042.436868,316102.632656693,352189.294859767,n.a.,4407.53126144409,370094.890609384

In [4]:
useful_fields = ['Company name Latin alphabet', 'NACE Rev. 2, core code (4 digits)', 'Consolidation code', 'year',
                 'Total shareholders\' equity ', 'Total liabilities ', 'Total current assets ', 'Net Cash from Operating Activities ',
                 'Net Cash from Financing Activities ', 'Net Cash from Investing Activities ', 'Total current liabilities ',
                 'Depreciation, Depletion & Amortization ', 'EBITDA ', 'Total depreciation, amortization & depletion ',
                 'Net property, plant & equipment ', 'Total long-term interest-bearing debt ', 'Net debt ', 'Net Income/Starting Line ',
                 'Net profit ', 'Earnings before interest & tax (EBIT) ', 'Increase/Decrease in Long Term Borrowings ', 'Increase/Decrease in Short Term Borrowings ',
                 'Loans & Borrowings ', 'Total assets ', 'Income tax expense ', 'Intangible assets ']
sgx = sgx[useful_fields]

In [5]:
colname_mapping = {
    'Company name Latin alphabet' : 'Company',
    'NACE Rev. 2, core code (4 digits)' : 'NACE',
    'year' : 'Year',
    'Total shareholders\' equity ' : 'TE',
    'Total liabilities ' : 'TL',
    'Total current assets ' : 'CA',
    'Net Cash from Operating Activities ' : 'CFO',
    'Net Cash from Financing Activities ' : 'CFF',
    'Net Cash from Investing Activities ' : 'CFI',
    'Total current liabilities ' : 'CL',
    'Depreciation, Depletion & Amortization ' : 'DA',
    'EBITDA ' : 'EBIDTA',
    'Total depreciation, amortization & depletion ' : 'TDA', # need to check if this duplicates with DA
    'Net property, plant & equipment ' : 'FA', # fixed assets
    'Total long-term interest-bearing debt ' : 'LTD',
    'Net debt ' : 'ND',
    'Net Income/Starting Line ' : 'NI', # net income from cashflow statement
    'Net profit ' : 'NP', # need to check if this duplicates with NI
    'Earnings before interest & tax (EBIT) ' : 'EBIT',
    'Increase/Decrease in Long Term Borrowings ' : 'DeltaLTB',
    'Increase/Decrease in Short Term Borrowings ' : 'DeltaSTB',
    'Loans & Borrowings ' : 'LB',
    'Total assets ' : 'TA',
    'Income tax expense ' : 'ITE', # can be used to calculate tax coverage & interest expense with EBIT
    'Intangible assets ' : 'IA'
}

sgx = sgx.rename(columns = colname_mapping)

In [6]:
sgx.to_csv("Data/filteredSGX.csv")

In [28]:
sgx.replace('n.a.', pd.NA, inplace = True)
sgx.dropna(inplace = True)

,Company,NACE,Consolidation code,Year,TE,TL,CA,CFO,CFF,CFI,...,ND,NI,NP,EBIT,DeltaLTB,DeltaSTB,LB,TA,ITE,IA
34,8I HOLDINGS LIMITED,7022.0,C1,2018,23843204.4112086,7620768.69624853,27840549.4546294,-4644885.43975353,252230.997204781,3112324.000597,...,-24135261.3553405,-8248396.11911774,-7521203.82893085,-5129434.46069956,36138.3592486382,0,0,31463973.1074572,-245593.339383602,134965.709030628
62,A SONIC AEROSPACE LIMITED,2611.0,C1,2006,61099000,63182000,83867000,3414000,4688000,9481000,...,1469000,7149000,5442000,7280000,-166000,5581000,7519000,124281000,-1626000,23937000
63,A SONIC AEROSPACE LIMITED,2611.0,C1,2007,49096000,59414000,89921000,5333000,-9831000,5590000,...,-6492000,-9529000,-10932000,289000,-16640000,8619000,10509000,108510000,-1333000,12542000
83,A-SMART HOLDINGS LTD,1812.0,C1,2007,67627172.5063324,12083084.8755836,17888469.353199,-723688.539028168,-2028180.12857437,-2197525.89273453,...,3065422.93405533,4558443.98760796,4688099.33829308,3671363.24644089,145531.516075134,-304293.169975281,2634781.94785118,79710257.381916,52259.0444087982,42656610.3754044
84,A-SMART HOLDINGS LTD,1812.0,C1,2008,81143610.4922295,23332846.2207317,37105148.2754946,92132.2038173676,5369260.10024548,3558057.96647072,...,3390611.34207249,7539485.34572124,7483182.3322773,7667446.73991203,100906.699419022,-347323.78423214,2755922.82688618,104476456.712961,-69464.7568464279,47151214.5314217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11976,YKGI LIMITED,5610.0,C1,2020,6221919.7883606,16414038.5761261,11370547.0676422,7969140.15197754,-4386960.22033691,-1199606.70852661,...,2602677.60658264,3810604.41207886,3721352.46276855,4759095.46661377,-3197942.72613525,679978.834152222,1890931.12945557,22635958.3644867,-470463.665008545,155056.352615356
11990,YOMA STRATEGIC HOLDINGS LTD,5510.0,C1,2014,531922253.856957,74034869.273603,248833993.303776,-14825281.1554074,195450049.796999,-178478019.692004,...,13499454.8159838,28561568.5120225,20378495.6970811,25146385.1577044,953142.004013062,7264801.85985565,7264801.85985565,605957123.13056,-2839811.04701757,23384670.7066894
11991,YOMA STRATEGIC HOLDINGS LTD,5510.0,C1,2015,545041056.325734,156911399.385154,268142984.110832,10088816.1253333,44408998.3373284,-58584854.4923067,...,36231957.7274919,32569756.7012906,27524238.432169,34815334.2909217,-8806157.60099888,54045590.3666615,43382427.4352789,701952455.710888,-2595662.69177198,22549033.2385302
11997,YOMA STRATEGIC HOLDINGS LTD,5510.0,C1,2021,681403000,547998000,553299000,4194000,32553000,-40473000,...,384777000,-15680000,-19704000,-22147000,-4265000,21633000,90094000,1229401000,-2832000,164106000
12007,YONGMAO HOLDINGS LIMITED,2892.0,C1,2011,73440413.8748646,126774541.237637,129557535.357445,2353399.09212291,11997044.8689312,-11206806.0864955,...,34785599.4477421,-1618766.17495716,-2463339.83145654,2568355.47986627,13189711.2420201,-37017.6188796759,41787013.3808255,200214955.112502,-1695661.14293039,153154.44034338

In [30]:
sgx_reduced = sgx[(sgx['Year'] >= 2013) & (sgx['Year'] <= 2022)]
sgx_reduced

,Company,NACE,Consolidation code,Year,TE,TL,CA,CFO,CFF,CFI,...,ND,NI,NP,EBIT,DeltaLTB,DeltaSTB,LB,TA,ITE,IA
34,8I HOLDINGS LIMITED,7022.0,C1,2018,23843204.4112086,7620768.69624853,27840549.4546294,-4644885.43975353,252230.997204781,3112324.000597,...,-24135261.3553405,-8248396.11911774,-7521203.82893085,-5129434.46069956,36138.3592486382,0,0,31463973.1074572,-245593.339383602,134965.709030628
178,ABR HOLDINGS LTD,5610.0,C1,2022,72330802.8645515,50895432.294488,33183101.9393206,16046407.4463844,-1869700.97887516,-20990628.6506653,...,12873716.763854,2062323.31520319,1809460.01654863,2846943.25661659,4103822.59404659,43879.2194724083,1637661.71658039,123226235.159039,-192622.33632803,11322326.0550499
252,ACCRELIST LIMITED,2611.0,C1,2016,29617255.8792233,6649735.34137011,21640435.1093173,6647589.11156654,3260838.48154545,-15887108.4159017,...,-2122621.27572298,-5946487.37573624,-5946487.37573624,-802689.946532249,-86564.6020770073,2861639.73808289,51509.5152854919,36266991.2205935,24323.9377737045,12877.378821373
289,ACMA LIMITED,4651.0,C1,2013,81667589.9218321,22162333.3712816,36607919.6119308,626728.848278522,-2894965.66361189,2611238.48009109,...,-148581.366300583,519244.455635548,354066.234588623,93258.5171461105,-3051450.2940774,-5532.28491544724,4043309.94677544,103829923.293114,-187307.360708714,2721093.85198355
313,ACROMEC LIMITED,7112.0,C1,2017,5724381.39724731,11572437.7012253,14329357.4970961,3424617.06018448,-454210.818171501,60365.1330471039,...,-6653415.51804543,-3339958.64188671,-3349528.72395515,-3259717.18454361,-255447.575211525,0,77296.8167066574,17296819.0984726,-9570.0820684433,204652.524232864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11975,YKGI LIMITED,5610.0,C1,2019,3731443.09037924,14268112.0117903,7828088.09053898,4353473.98549318,-1656769.63949203,-1700564.17745352,...,3372921.70333862,883313.562273979,771971.516609192,1387321.88898325,-1923248.26878309,671021.395206451,1188390.7673955,17999555.1021695,-129156.772971153,170724.470019341
11976,YKGI LIMITED,5610.0,C1,2020,6221919.7883606,16414038.5761261,11370547.0676422,7969140.15197754,-4386960.22033691,-1199606.70852661,...,2602677.60658264,3810604.41207886,3721352.46276855,4759095.46661377,-3197942.72613525,679978.834152222,1890931.12945557,22635958.3644867,-470463.665008545,155056.352615356
11990,YOMA STRATEGIC HOLDINGS LTD,5510.0,C1,2014,531922253.856957,74034869.273603,248833993.303776,-14825281.1554074,195450049.796999,-178478019.692004,...,13499454.8159838,28561568.5120225,20378495.6970811,25146385.1577044,953142.004013062,7264801.85985565,7264801.85985565,605957123.13056,-2839811.04701757,23384670.7066894
11991,YOMA STRATEGIC HOLDINGS LTD,5510.0,C1,2015,545041056.325734,156911399.385154,268142984.110832,10088816.1253333,44408998.3373284,-58584854.4923067,...,36231957.7274919,32569756.7012906,27524238.432169,34815334.2909217,-8806157.60099888,54045590.3666615,43382427.4352789,701952455.710888,-2595662.69177198,22549033.2385302
11997,YOMA STRATEGIC HOLDINGS LTD,5510.0,C1,2021,681403000,547998000,553299000,4194000,32553000,-40473000,...,384777000,-15680000,-19704000,-22147000,-4265000,21633000,90094000,1229401000,-2832000,164106000